table 'OU PP (WS4)'
	lineageTag: decbc497-3868-4a62-a182-39bf9f606abc

	column 'Product Group'
		dataType: string
		lineageTag: df2de34d-afb8-432d-a73c-ac4ada29ba91
		summarizeBy: none
		sourceColumn: Product Group

		annotation SummarizationSetBy = Automatic

	column 'Sales 21/22'
		dataType: int64
		formatString: 0
		lineageTag: 30615ce4-fa95-44a7-936f-53491be7a618
		summarizeBy: sum
		sourceColumn: Sales 21/22

		annotation SummarizationSetBy = Automatic

	column 'Actual 22/23'
		dataType: int64
		formatString: 0
		lineageTag: 8987330b-0d37-4e7c-bd53-a096b7ce5b00
		summarizeBy: sum
		sourceColumn: Actual 22/23

		annotation SummarizationSetBy = Automatic

	column Orderbacklog
		dataType: int64
		formatString: 0
		lineageTag: 27b48731-08a6-450b-93b1-139aeef2caa1
		summarizeBy: sum
		sourceColumn: Orderbacklog

		annotation SummarizationSetBy = Automatic

	column 'Pipeline X/Y'
		dataType: int64
		formatString: 0
		lineageTag: 24d0f849-dfb3-4675-a977-4ea7bd591ee9
		summarizeBy: sum
		sourceColumn: Pipeline X/Y

		annotation SummarizationSetBy = Automatic

	partition 'OU PP (WS4)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Pranjali.Waghchaure\Desktop\Data\Capstone 2-Finance\Input data template.xlsx"), null, true),
				    #"OU PP (WS4)_Sheet" = Source{[Item="OU PP (WS4)",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"OU PP (WS4)_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product Group", type text}, {"Sales 21/22", Int64.Type}, {"Actual 22/23", Int64.Type}, {"Orderbacklog", Int64.Type}, {"Pipeline X/Y", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

