table 'Sales Grey'
	lineageTag: 34da339d-66ed-417f-9b4d-191492de8fba

	column 'Product Group'
		dataType: string
		lineageTag: 5224aaca-2fa1-4c26-b1a6-5084d8f12d71
		summarizeBy: none
		sourceColumn: Product Group

		annotation SummarizationSetBy = Automatic

	column 'target 24/25'
		dataType: int64
		formatString: 0
		lineageTag: d543c4b8-1480-45af-ae69-83f8f39e9859
		summarizeBy: sum
		sourceColumn: target 24/25

		annotation SummarizationSetBy = Automatic

	column 'Order Intake 23/24'
		dataType: int64
		formatString: 0
		lineageTag: d0098c55-c9e2-4eeb-bcb2-b3ecb6caa47b
		summarizeBy: sum
		sourceColumn: Order Intake 23/24

		annotation SummarizationSetBy = Automatic

	column 'Order Intake 22/23 actual'
		dataType: int64
		formatString: 0
		lineageTag: 55370db0-e4f2-45f2-8d84-1be94b846dd7
		summarizeBy: sum
		sourceColumn: Order Intake 22/23 actual

		annotation SummarizationSetBy = Automatic

	partition 'Sales Grey' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Pranjali.Waghchaure\Desktop\Data\Capstone 2-Finance\Input data template.xlsx"), null, true),
				    #"Sales Grey_Sheet" = Source{[Item="Sales Grey",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Sales Grey_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product Group", type text}, {"target 24/25", Int64.Type}, {"Order Intake 23/24", Int64.Type}, {"Order Intake 22/23 actual", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

